GET http://localhost:3001/products?sortField=name&sortOrder=desc

###
GET http://localhost:3001/products?query=4

###

GET http://localhost:3001/products/count

###

GET http://localhost:3001/products?limit=200
###

GET http://localhost:3001/products/1

### 

POST http://localhost:3001/products HTTP/1.1
content-type: application/json

{
    "product": {
        "sku": "PR4",
        "name": "Product 4",
        "price": 4.50,
        "inStock": 2
    }    
}

### 

POST http://localhost:3001/products/1/edit HTTP/1.1
content-type: application/json

{
    "product": {
        "name": "Product 1 1"
    }    
}

###
POST http://localhost:3001/products/43/delete HTTP/1.1
content-type: application/json

###
GET http://localhost:3001/orders?limit=10

###
GET http://localhost:3001/orders/count

###
POST http://localhost:3001/orders
content-type: application/json

{
    "products": [
        {"id": 1, "count": 1},
        {"id": 2, "count": 2}
    ],
    "client": {
        "name": "Pepe",
        "email": "pe@pe.ga",
        "phoneNumber": "1111",
        "address": "pepegia"
    }
}

###
POST http://localhost:3001/orders/2/delete