GET http://localhost:3001/products

###
GET http://localhost:3001/products?query=Qwe

###

GET http://localhost:3001/products/count

###

GET http://localhost:3001/products?limit=200&offset=0

###

GET http://localhost:3001/products/1

### 

POST http://localhost:3001/products HTTP/1.1
content-type: application/json

{
    "product": {
        "name": "Product 3",
        "price": 4.50
    }    
}

### 

POST http://localhost:3001/products/1/edit HTTP/1.1
content-type: application/json

{
    "product": {
        "name": "Product 1 1"
    }    
}

###
POST http://localhost:3001/products/43/delete HTTP/1.1
content-type: application/json

###
GET http://localhost:3001/orders?limit=10&offset=2